!obj:pylearn2.train.Train {
    dataset: !obj:pylearn2.sandbox.nlp.datasets.pytables_file.PytablesFile {
        filename: 'joint_paper_hs/combined_train.hdf',
        node: '/combined_train',
        vocab_size: 15000
    },
    model: !obj:pylearn2.models.mlp.MLP {
        layers: [
            !obj:pylearn2.sandbox.nlp.models.mlp.ProjectionLayer {
                layer_name: 'projection',
                dim: 512,
                irange: 0.01
            }, !obj:pylearn2.models.mlp.RectifiedLinear {
                layer_name: 'rectified_linear_0',
                dim: 1536,
                irange: 0.01
            }, !obj:pylearn2.models.mlp.RectifiedLinear {
                layer_name: 'rectified_linear_1',
                dim: 1024,
                irange: 0.01
            }, !obj:pylearn2.models.mlp.Softmax {
                n_classes: 15000,
                layer_name: 'softmax',
                irange: 0.01
            }
        ],
        input_space: !obj:pylearn2.space.IndexSpace {
            dim: 6,
            max_labels: 15000
        }
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 256,
        monitoring_batch_size: 256,
        batches_per_iter: 100000,
        monitoring_batches: 4000,
        learning_rate: .1,
        monitoring_dataset: {
            'valid' : !obj:pylearn2.sandbox.nlp.datasets.pytables_file.PytablesFile {
                filename: 'joint_paper_hs/combined_valid.hdf',
                node: '/combined_valid',
                vocab_size: 15000
            }
        },
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: 'valid_softmax_nll',
            prop_decrease: 0.,
            N: 5
        },
        cost: !obj:pylearn2.costs.mlp.dropout.Dropout {
            input_include_probs: {
              'projection': 1
            },
            input_scales: {
              'projection': 1
            }
        }
    },
    extensions: [
      !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
        channel_name: 'valid_softmax_nll',
        save_path: 'holger_best.pkl'
      },
      !obj:pylearn2.training_algorithms.sgd.MonitorBasedLRAdjuster {
        high_trigger: 1.,
        shrink_amt: .5,
        low_trigger: 1.,
        channel_name: 'valid_softmax_nll'
      }
    ]
}
